"""add min_kp_notification

Revision ID: 4a0fd7ca68ff
Revises: 123456789abc
Create Date: 2025-12-26 22:43:24.223566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0fd7ca68ff'
down_revision: Union[str, Sequence[str], None] = '123456789abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('min_kp_notification', sa.Integer(), nullable=False, server_default="1"))

    op.alter_column("profiles", "min_kp_notification", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'min_kp_notification')
    # ### end Alembic commands ###
